name: dollars-and-sense

up:
  - python: 3.11
  - pip:
      requirements: tools/requirements.txt

commands:
  server: python tools/ndcg_server.py --port 8080
  test: python -m pytest tests/ -v --tb=short
  test-cov: python -m pytest tests/ -v --cov=tools --cov-report=term-missing
  lint: python -m py_compile tools/*.py

